import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/exercise.dart';
import 'difficulty_inference.dart';

class ExerciseDBService {
  static const _base = 'https://oss.exercisedb.dev/api/v1';
  static const _cacheCollection = 'exercises';
  static const _metaDoc = 'cache_meta';
  static const _cacheTtlDays = 30;

  // ── Demo-GIF media source ───────────────────────────────────────────────────
  // The AscendAPI JSON metadata (names/muscles/equipment/…) at [_base] is still
  // live and authoritative, but its free media CDN `static.exercisedb.dev` was
  // pulled from DNS (NXDOMAIN) — every gifUrl it advertises now fails to load.
  // We therefore ignore the API's gifUrl entirely and resolve each exercise's
  // demo animation by NAME against JahelCuadrado/ExerciseGymGifsDB, a free
  // GitHub-hosted GIF library served over the jsDelivr CDN (no key, no rate
  // limit, pinned to a version tag so it can't shift under us). Files are named
  // by the same slugified exercise names as the ExerciseDB catalog, giving
  // ~95% coverage; unmatched exercises resolve to null → existing placeholder.
  static const _gifRepoRef = 'v1.2.0';
  static const _gifRepo = 'JahelCuadrado/ExerciseGymGifsDB';
  static const _gifCdnBase = 'https://cdn.jsdelivr.net/gh/$_gifRepo@$_gifRepoRef';

  // slug → full jsDelivr .gif URL, built once per cache rebuild from the repo
  // tree at the pinned tag. Empty when the index build fails (→ placeholders).
  Map<String, String> _gifIndex = {};

  /// Bump this when the upstream API/media host changes so the existing
  /// Firestore cache (which may hold dead gifUrls) is treated as stale and
  /// refreshed exactly once. v2 = AscendAPI / oss.exercisedb.dev migration.
  /// v3 = re-infer difficulty (default-to-beginner) for the strict level gate.
  /// v4 = rebuilt difficulty classifier (difficulty_inference.dart) — fixes
  ///      hard moves labeled beginner and 'lever …' machine moves labeled
  ///      advanced; cached docs must be re-labeled once.
  /// v5 = drop exercises whose gifUrl 404s on the CDN (~7% of the catalog)
  ///      so every cached exercise has a working demo animation.
  /// v6 = drop auto-generated junk exercise names (style-prefix / 'gentle' /
  ///      dangling "with ADJECTIVE") so the catalog reads professionally.
  /// v7 = re-infer locations: barbell is no longer gym-only (home users can own
  ///      a barbell), so barbell/ez-barbell moves become ['home','gym'] and are
  ///      gated by the user's equipment instead. Cached docs must be re-labeled.
  /// v8 = swap the demo-GIF media host: the free `static.exercisedb.dev` CDN was
  ///      removed from DNS, so gifUrls are now resolved by name against the
  ///      jsDelivr-hosted ExerciseGymGifsDB (see _gifCdnBase). Cached docs hold
  ///      dead URLs and must be rebuilt once.
  static const _cacheVersion = 10;

  final _db = FirebaseFirestore.instance;

  // ── Public API ──────────────────────────────────────────────────────────────

  /// Returns exercises from Firestore cache; refreshes if stale or empty.
  Future<List<Exercise>> getExercises() async {
    final meta = await _db
        .collection(_cacheCollection)
        .doc(_metaDoc)
        .get();

    final needsRefresh = _isCacheStale(meta);
    if (!needsRefresh) {
      final cached = await _loadFromFirestore();
      if (cached.isNotEmpty) return cached;
    }

    // Build the name→GIF index first so _mapToExercise can resolve each demo
    // animation as the catalog is parsed, then fetch, drop auto-generated junk
    // names, and cache. (No GIF HEAD-check pass any more — the jsDelivr media
    // host is reliable and unmatched exercises simply carry a null gifUrl.)
    await _buildGifIndex();
    final fresh = await _fetchFromApi();
    if (fresh.isNotEmpty) {
      // Junk-name filter (cheap, in-memory). Same <50% safety guard: never gut
      // the catalog if the heuristic somehow over-matches.
      final cleaned =
          fresh.where((e) => !_isLikelyAutoGenerated(e.name)).toList();
      final pool = cleaned.length >= fresh.length * 0.5 ? cleaned : fresh;
      if (kDebugMode) {
        final resolved = pool.where((e) => e.gifUrl != null).length;
        final pct = pool.isEmpty ? 0 : (resolved * 100 / pool.length).round();
        debugPrint(
          'ExerciseDBService: GIF coverage $resolved/${pool.length} ($pct%) '
          'resolved from $_gifRepo@$_gifRepoRef',
        );
      }
      await _saveToFirestore(pool);
      return pool;
    }
    return await _loadFromFirestore();
  }

  // ── Demo-GIF resolution ─────────────────────────────────────────────────────

  /// Fetches the ExerciseGymGifsDB file tree once (at the pinned tag) and builds
  /// [_gifIndex] as slug → jsDelivr `.gif` URL. Called only on a cache rebuild
  /// (~30-day TTL), so the single GitHub API call is well under any rate limit.
  /// On any failure the index stays empty → all gifUrls resolve to null and the
  /// UI shows its placeholder (no crash, no broken images).
  Future<void> _buildGifIndex() async {
    final uri = Uri.parse(
      'https://api.github.com/repos/$_gifRepo/git/trees/$_gifRepoRef?recursive=1',
    );
    try {
      final resp = await http.get(uri, headers: {
        'Accept': 'application/vnd.github+json',
        'User-Agent': 'OneFit/1.0',
      }).timeout(const Duration(seconds: 30));
      if (resp.statusCode != 200) {
        if (kDebugMode) debugPrint('ExerciseDBService: GitHub GIF index ${resp.statusCode}');
        return;
      }
      final json = jsonDecode(resp.body) as Map<String, dynamic>;
      final tree = json['tree'] as List? ?? [];
      final index = <String, String>{};
      for (final node in tree) {
        final path = (node as Map)['path'] as String? ?? '';
        if (!path.endsWith('.gif')) continue; // ignore .thumb.webp etc.
        // path is "{muscleFolder}/{slug}.gif"
        final slash = path.lastIndexOf('/');
        final slug = path.substring(slash + 1, path.length - 4); // strip ".gif"
        index[slug] = '$_gifCdnBase/$path';
      }
      if (index.isNotEmpty) _gifIndex = index;
    } catch (e) {
      if (kDebugMode) debugPrint('ExerciseDBService: _buildGifIndex failed – $e');
    }
  }

  /// Matches the ExerciseGymGifsDB file-naming convention (verified to align
  /// with the ExerciseDB catalog names): lowercase, `/`→`-`, drop any char
  /// outside `[a-z0-9 -]`, collapse whitespace, then spaces→`-`.
  String _slugify(String name) => name
      .toLowerCase()
      .replaceAll('/', '-')
      .replaceAll(RegExp(r'[^a-z0-9 -]'), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim()
      .replaceAll(' ', '-');

  /// Resolved demo-GIF URL for [name], or null if the library has no match.
  String? _resolveGif(String name) => _gifIndex[_slugify(name)];

  // ── Junk-name filter ──────────────────────────────────────────────────────
  // The upstream catalog contains auto-generated variants with broken/marketing
  // names ("gentle style cable pulldown (pro lat bar)", "band underhand
  // pulldown with classic"). Tuned for PRECISION against a live catalog sample:
  // " with " and "(...)" are mostly legitimate ("calf stretch with rope",
  // "pull up (neutral grip)") and are NOT filtered — only the specific generator
  // signatures below are.
  static final _stylePrefix = RegExp(r'\b[a-z-]+ style ');
  static final _gentleWord = RegExp(r'\bgentle\b');
  // Adjectives that, when left dangling after "with" (no object noun), mark a
  // generated name. The tail after "with" must equal the adjective EXACTLY, so
  // legit two-word objects survive ("with single arm", "with stability ball",
  // "with v-bar") — only bare "...with classic" / "...with mega" are dropped.
  static const _danglingWithAdjectives = {
    'classic', 'simple', 'basic', 'intensified', 'declined', 'elevated',
    'extended', 'advanced', 'dynamic', 'narrow', 'targeted', 'traditional',
    'mega', 'horizontal', 'vertical', 'fierce', 'sharp', 'firm', 'precision',
    'complete', 'athletic', 'endurance', 'macro', 'high', 'triple', 'single',
    'inverted', 'stability',
  };

  bool _isLikelyAutoGenerated(String name) {
    final n = name.toLowerCase();
    if (_stylePrefix.hasMatch(n)) return true;
    if (_gentleWord.hasMatch(n)) return true;
    final withIdx = n.lastIndexOf(' with ');
    if (withIdx != -1) {
      final tail = n.substring(withIdx + ' with '.length).trim();
      if (_danglingWithAdjectives.contains(tail)) return true;
    }
    return false;
  }

  // ── Firestore cache ─────────────────────────────────────────────────────────

  Future<List<Exercise>> _loadFromFirestore() async {
    final snap = await _db.collection(_cacheCollection).get();
    return snap.docs
        .where((d) => d.id != _metaDoc)
        .map((d) => Exercise.fromMap(d.data()))
        .toList();
  }

  Future<void> _saveToFirestore(List<Exercise> exercises) async {
    const chunkSize = 499; // Firestore batch limit is 500 ops

    // Purge the previous cache generation first. Old-host docs use numeric IDs
    // and new-host docs use alphanumeric IDs, so a plain overwrite-by-ID leaves
    // the old docs (with dead gifUrls) behind; _loadFromFirestore would then
    // return the union. Delete every non-meta doc so the cache holds exactly
    // one clean generation.
    final existing = await _db.collection(_cacheCollection).get();
    final staleDocs = existing.docs.where((d) => d.id != _metaDoc).toList();
    for (int i = 0; i < staleDocs.length; i += chunkSize) {
      final chunk = staleDocs.sublist(i, (i + chunkSize).clamp(0, staleDocs.length));
      final batch = _db.batch();
      for (final doc in chunk) {
        batch.delete(doc.reference);
      }
      await batch.commit();
    }

    for (int i = 0; i < exercises.length; i += chunkSize) {
      final chunk = exercises.sublist(i, (i + chunkSize).clamp(0, exercises.length));
      final batch = _db.batch();
      for (final ex in chunk) {
        final rawId = ex.id.isNotEmpty ? ex.id : ex.name;
        final safeId = rawId.replaceAll(RegExp(r'[/\\.#\[\]*?]'), '_');
        if (safeId.isEmpty) continue;
        final ref = _db.collection(_cacheCollection).doc(safeId);
        batch.set(ref, ex.toMap());
      }
      await batch.commit();
    }

    // Write cache metadata in a separate batch
    await _db.collection(_cacheCollection).doc(_metaDoc).set(
      {
        'updatedAt': FieldValue.serverTimestamp(),
        'count': exercises.length,
        'version': _cacheVersion,
      },
    );
  }

  bool _isCacheStale(DocumentSnapshot meta) {
    if (!meta.exists) return true;
    final data = meta.data() as Map<String, dynamic>?;
    if (data == null) return true;
    // Cache written by an older app version (or no version) → force a refresh
    // so dead gifUrls from the retired host get overwritten.
    if (data['version'] != _cacheVersion) return true;
    final ts = data['updatedAt'];
    if (ts == null) return true;
    final updatedAt = (ts as Timestamp).toDate();
    return DateTime.now().difference(updatedAt).inDays >= _cacheTtlDays;
  }

  // ── HTTP fetch ──────────────────────────────────────────────────────────────

  // The AscendAPI free tier serves a fixed 25 exercises per page and ignores
  // `limit`/`offset`; pages are walked with `?after=<meta.nextCursor>`.
  Future<List<Exercise>> _fetchFromApi() async {
    const maxPages = 100; // safety stop (~1500 exercises / 25 ≈ 60 pages)
    final exercises = <Exercise>[];
    String? cursor;

    try {
      int retries = 0;
      for (int page = 0; page < maxPages; page++) {
        final uri = Uri.parse('$_base/exercises').replace(
          queryParameters: cursor == null ? null : {'after': cursor},
        );
        final response = await http
            .get(uri, headers: {'Content-Type': 'application/json'})
            .timeout(const Duration(seconds: 30));

        // The free tier rate-limits rapid pagination (HTTP 429). Back off and
        // retry the same page a few times so the full catalog is fetched.
        if (response.statusCode == 429 && retries < 4) {
          retries++;
          page--; // don't count this attempt
          await Future.delayed(Duration(milliseconds: 1500 * retries));
          continue;
        }
        if (response.statusCode != 200) break;
        retries = 0;

        final json = jsonDecode(response.body) as Map<String, dynamic>;
        final rawList = json['data'] as List? ?? [];
        exercises.addAll(rawList.cast<Map<String, dynamic>>().map(_mapToExercise));

        final meta = json['meta'] as Map<String, dynamic>? ?? {};
        final hasNext = meta['hasNextPage'] == true;
        cursor = meta['nextCursor'] as String?;
        if (!hasNext || cursor == null || cursor.isEmpty) break;

        // Gentle pacing between pages to stay under the rate limit.
        await Future.delayed(const Duration(milliseconds: 350));
      }
    } catch (_) {
      // Return whatever was gathered before the failure.
    }

    return exercises;
  }

  // ── Mapping ─────────────────────────────────────────────────────────────────

  Exercise _mapToExercise(Map<String, dynamic> raw) {
    final bodyParts = List<String>.from(raw['bodyParts'] ?? (raw['bodyPart'] is String ? [raw['bodyPart']] : []));
    final equipments = List<String>.from(raw['equipments'] ?? (raw['equipment'] is String ? [raw['equipment']] : []));
    final targetMuscles = List<String>.from(raw['targetMuscles'] ?? (raw['target'] is String ? [raw['target']] : []));
    final secondaryMuscles = List<String>.from(raw['secondaryMuscles'] ?? []);
    final instructions = raw['instructions'] is List
        ? (raw['instructions'] as List).cast<String>().join('\n')
        : (raw['instructions'] as String? ?? '');
    final name = (raw['name'] as String? ?? '').toLowerCase();

    // If the exact name slug has no GIF match, try stripping parenthetical
    // qualifiers (e.g. "(Competition Grip)", "(Smith Machine)"). When the
    // stripped version matches, rename the exercise to the cleaner base form
    // so the display name and GIF align without needing a fuzzy lookup.
    String displayName = name;
    if (!_gifIndex.containsKey(_slugify(name))) {
      final stripped = name.replaceAll(RegExp(r'\s*\(.*?\)'), '').trim();
      if (stripped.isNotEmpty && _gifIndex.containsKey(_slugify(stripped))) {
        displayName = stripped;
      }
    }

    return Exercise(
      id: raw['exerciseId']?.toString() ?? raw['id']?.toString() ?? name.hashCode.toString(),
      name: _titleCase(displayName),
      category: bodyParts.isNotEmpty ? bodyParts.first : 'Other',
      primaryMuscles: targetMuscles,
      secondaryMuscles: secondaryMuscles,
      equipment: _normalizeEquipment(equipments),
      difficulty: inferExerciseDifficulty(name, equipments),
      goals: _inferGoals(bodyParts, name),
      locations: _inferLocations(equipments),
      instructions: instructions,
      gifUrl: _resolveGif(displayName),
    );
  }

  // Maps ExerciseDB equipment names to app's format
  List<String> _normalizeEquipment(List<String> raw) {
    const map = {
      'body weight': 'Bodyweight',
      'dumbbell': 'Dumbbells',
      'barbell': 'Barbell',
      'ez barbell': 'Barbell',
      'kettlebell': 'Kettlebells',
      'resistance band': 'Resistance Bands',
      'pull-up bar': 'Pull-up Bar',
      'cable': 'Cable Machine',
      'machine': 'Machine',
      'band': 'Resistance Bands',
      'assisted': 'Machine',
    };
    final normalized = raw.map((e) => map[e.toLowerCase()] ?? _titleCase(e)).toList();
    return normalized.isEmpty ? ['Bodyweight'] : normalized;
  }

  // Infers workout goal tags from body parts / exercise name
  List<String> _inferGoals(List<String> bodyParts, String name) {
    final goals = <String>[];
    final bp = bodyParts.map((b) => b.toLowerCase()).toList();

    // "jump" as a standalone movement (starts the name or follows a named
    // plyometric pattern). Bare name.contains('jump') was too broad —
    // "barbell incline jump" matched because the lowercased name contains the
    // substring, even though the exercise is a strength move, not a cardio one.
    final isJumpMove = name.startsWith('jump') ||
        RegExp(r'\b(box|broad|depth|split|vertical|long)\s+jump\b').hasMatch(name);
    if (bp.contains('cardio') || name.contains('run') || isJumpMove) {
      goals.add('weight_loss');
      goals.add('endurance');
    }
    if (bp.any((b) => ['chest', 'back', 'shoulders', 'upper arms', 'upper legs'].contains(b))) {
      goals.add('muscle_gain');
      goals.add('general');
    }
    if (bp.contains('waist') || bp.contains('lower legs')) {
      goals.add('weight_loss');
      goals.add('general');
    }
    if (goals.isEmpty) goals.addAll(['general', 'muscle_gain']);
    return goals.toSet().toList();
  }

  // Infers home/gym from equipment. Barbell is intentionally NOT gym-only:
  // home users can own a barbell, so barbell/ez-barbell moves stay home-eligible
  // and are gated by the user's equipment chips (and rack) in
  // GreedyAlgorithm.isEligibleForUser. Only fixed-station gym kit is gym-only.
  List<String> _inferLocations(List<String> raw) {
    final gymOnly = {'cable', 'machine', 'assisted', 'smith machine', 'leverage machine'};
    final hasGymEquip = raw.any((e) => gymOnly.contains(e.toLowerCase()));
    return hasGymEquip ? ['gym'] : ['home', 'gym'];
  }

  // Difficulty inference lives in difficulty_inference.dart (pure Dart, no
  // Firebase) so it can be audited by a standalone script against the full
  // catalog. See that file for the tier policy and keyword rationale.

  String _titleCase(String s) => s.split(' ').map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}').join(' ');
}
