import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/exercise.dart';
import 'difficulty_inference.dart';

class ExerciseDBService {
  static const _base = 'https://oss.exercisedb.dev/api/v1';
  static const _cacheCollection = 'exercises';
  static const _metaDoc = 'cache_meta';
  static const _cacheTtlDays = 30;

  /// Bump this when the upstream API/media host changes so the existing
  /// Firestore cache (which may hold dead gifUrls) is treated as stale and
  /// refreshed exactly once. v2 = AscendAPI / oss.exercisedb.dev migration.
  /// v3 = re-infer difficulty (default-to-beginner) for the strict level gate.
  /// v4 = rebuilt difficulty classifier (difficulty_inference.dart) — fixes
  ///      hard moves labeled beginner and 'lever …' machine moves labeled
  ///      advanced; cached docs must be re-labeled once.
  /// v5 = drop exercises whose gifUrl 404s on the CDN (~7% of the catalog)
  ///      so every cached exercise has a working demo animation.
  /// v6 = drop auto-generated junk exercise names (style-prefix / 'gentle' /
  ///      dangling "with ADJECTIVE") so the catalog reads professionally.
  /// v7 = re-infer locations: barbell is no longer gym-only (home users can own
  ///      a barbell), so barbell/ez-barbell moves become ['home','gym'] and are
  ///      gated by the user's equipment instead. Cached docs must be re-labeled.
  static const _cacheVersion = 7;

  final _db = FirebaseFirestore.instance;

  // ── Public API ──────────────────────────────────────────────────────────────

  /// Returns exercises from Firestore cache; refreshes if stale or empty.
  Future<List<Exercise>> getExercises() async {
    final meta = await _db
        .collection(_cacheCollection)
        .doc(_metaDoc)
        .get();

    final needsRefresh = _isCacheStale(meta);
    if (!needsRefresh) {
      final cached = await _loadFromFirestore();
      if (cached.isNotEmpty) return cached;
    }

    // Fetch from API, drop auto-generated junk names, drop exercises whose
    // demo GIF is missing, then cache.
    final fresh = await _fetchFromApi();
    if (fresh.isNotEmpty) {
      // Junk-name filter runs first (cheap, in-memory) so we don't waste GIF
      // HEAD checks on names we're discarding anyway. Same <50% safety guard:
      // never gut the catalog if the heuristic somehow over-matches.
      final cleaned =
          fresh.where((e) => !_isLikelyAutoGenerated(e.name)).toList();
      final pool = cleaned.length >= fresh.length * 0.5 ? cleaned : fresh;
      final withGifs = await _keepExercisesWithWorkingGifs(pool);
      await _saveToFirestore(withGifs);
      return withGifs;
    }
    return await _loadFromFirestore();
  }

  // ── Junk-name filter ──────────────────────────────────────────────────────
  // The upstream catalog contains auto-generated variants with broken/marketing
  // names ("gentle style cable pulldown (pro lat bar)", "band underhand
  // pulldown with classic"). Tuned for PRECISION against a live catalog sample:
  // " with " and "(...)" are mostly legitimate ("calf stretch with rope",
  // "pull up (neutral grip)") and are NOT filtered — only the specific generator
  // signatures below are.
  static final _stylePrefix = RegExp(r'\b[a-z-]+ style ');
  static final _gentleWord = RegExp(r'\bgentle\b');
  // Adjectives that, when left dangling after "with" (no object noun), mark a
  // generated name. The tail after "with" must equal the adjective EXACTLY, so
  // legit two-word objects survive ("with single arm", "with stability ball",
  // "with v-bar") — only bare "...with classic" / "...with mega" are dropped.
  static const _danglingWithAdjectives = {
    'classic', 'simple', 'basic', 'intensified', 'declined', 'elevated',
    'extended', 'advanced', 'dynamic', 'narrow', 'targeted', 'traditional',
    'mega', 'horizontal', 'vertical', 'fierce', 'sharp', 'firm', 'precision',
    'complete', 'athletic', 'endurance', 'macro', 'high', 'triple', 'single',
    'inverted', 'stability',
  };

  bool _isLikelyAutoGenerated(String name) {
    final n = name.toLowerCase();
    if (_stylePrefix.hasMatch(n)) return true;
    if (_gentleWord.hasMatch(n)) return true;
    final withIdx = n.lastIndexOf(' with ');
    if (withIdx != -1) {
      final tail = n.substring(withIdx + ' with '.length).trim();
      if (_danglingWithAdjectives.contains(tail)) return true;
    }
    return false;
  }

  /// Keeps only exercises whose [Exercise.gifUrl] actually resolves on the CDN.
  /// The API advertises a gifUrl for every exercise, but ~7% 404 on
  /// static.exercisedb.dev and render as a broken "Exercise Demo" placeholder.
  /// HEAD-check each one (bounded concurrency) and drop the definitively-missing
  /// media so every cached exercise has a working animation.
  ///
  /// Conservative on purpose: only a definitive 404 (or a missing url) drops an
  /// exercise — timeouts / 5xx / 429 keep it (the UI still has a placeholder
  /// fallback). And if the pass would discard most of the catalog (< 50%
  /// survive → the network is the problem, not the media), keep everything
  /// rather than cache a gutted list.
  Future<List<Exercise>> _keepExercisesWithWorkingGifs(
    List<Exercise> exercises,
  ) async {
    const concurrency = 16;
    final kept = <Exercise>[];

    for (int i = 0; i < exercises.length; i += concurrency) {
      final chunk = exercises.sublist(
        i,
        (i + concurrency).clamp(0, exercises.length),
      );
      final results = await Future.wait(
        chunk.map((ex) async {
          final url = ex.gifUrl;
          if (url == null || url.isEmpty) return false; // no demo at all
          try {
            final resp = await http
                .head(Uri.parse(url))
                .timeout(const Duration(seconds: 8));
            return resp.statusCode != 404; // drop only definitively-missing
          } catch (_) {
            return true; // timeout/network error → keep, UI has a fallback
          }
        }),
      );
      for (int j = 0; j < chunk.length; j++) {
        if (results[j]) kept.add(chunk[j]);
      }
    }

    if (kept.length < exercises.length * 0.5) return exercises;
    return kept;
  }

  // ── Firestore cache ─────────────────────────────────────────────────────────

  Future<List<Exercise>> _loadFromFirestore() async {
    final snap = await _db.collection(_cacheCollection).get();
    return snap.docs
        .where((d) => d.id != _metaDoc)
        .map((d) => Exercise.fromMap(d.data()))
        .toList();
  }

  Future<void> _saveToFirestore(List<Exercise> exercises) async {
    const chunkSize = 499; // Firestore batch limit is 500 ops

    // Purge the previous cache generation first. Old-host docs use numeric IDs
    // and new-host docs use alphanumeric IDs, so a plain overwrite-by-ID leaves
    // the old docs (with dead gifUrls) behind; _loadFromFirestore would then
    // return the union. Delete every non-meta doc so the cache holds exactly
    // one clean generation.
    final existing = await _db.collection(_cacheCollection).get();
    final staleDocs = existing.docs.where((d) => d.id != _metaDoc).toList();
    for (int i = 0; i < staleDocs.length; i += chunkSize) {
      final chunk = staleDocs.sublist(i, (i + chunkSize).clamp(0, staleDocs.length));
      final batch = _db.batch();
      for (final doc in chunk) {
        batch.delete(doc.reference);
      }
      await batch.commit();
    }

    for (int i = 0; i < exercises.length; i += chunkSize) {
      final chunk = exercises.sublist(i, (i + chunkSize).clamp(0, exercises.length));
      final batch = _db.batch();
      for (final ex in chunk) {
        final rawId = ex.id.isNotEmpty ? ex.id : ex.name;
        final safeId = rawId.replaceAll(RegExp(r'[/\\.#\[\]*?]'), '_');
        if (safeId.isEmpty) continue;
        final ref = _db.collection(_cacheCollection).doc(safeId);
        batch.set(ref, ex.toMap());
      }
      await batch.commit();
    }

    // Write cache metadata in a separate batch
    await _db.collection(_cacheCollection).doc(_metaDoc).set(
      {
        'updatedAt': FieldValue.serverTimestamp(),
        'count': exercises.length,
        'version': _cacheVersion,
      },
    );
  }

  bool _isCacheStale(DocumentSnapshot meta) {
    if (!meta.exists) return true;
    final data = meta.data() as Map<String, dynamic>?;
    if (data == null) return true;
    // Cache written by an older app version (or no version) → force a refresh
    // so dead gifUrls from the retired host get overwritten.
    if (data['version'] != _cacheVersion) return true;
    final ts = data['updatedAt'];
    if (ts == null) return true;
    final updatedAt = (ts as Timestamp).toDate();
    return DateTime.now().difference(updatedAt).inDays >= _cacheTtlDays;
  }

  // ── HTTP fetch ──────────────────────────────────────────────────────────────

  // The AscendAPI free tier serves a fixed 25 exercises per page and ignores
  // `limit`/`offset`; pages are walked with `?after=<meta.nextCursor>`.
  Future<List<Exercise>> _fetchFromApi() async {
    const maxPages = 100; // safety stop (~1500 exercises / 25 ≈ 60 pages)
    final exercises = <Exercise>[];
    String? cursor;

    try {
      int retries = 0;
      for (int page = 0; page < maxPages; page++) {
        final uri = Uri.parse('$_base/exercises').replace(
          queryParameters: cursor == null ? null : {'after': cursor},
        );
        final response = await http
            .get(uri, headers: {'Content-Type': 'application/json'})
            .timeout(const Duration(seconds: 30));

        // The free tier rate-limits rapid pagination (HTTP 429). Back off and
        // retry the same page a few times so the full catalog is fetched.
        if (response.statusCode == 429 && retries < 4) {
          retries++;
          page--; // don't count this attempt
          await Future.delayed(Duration(milliseconds: 1500 * retries));
          continue;
        }
        if (response.statusCode != 200) break;
        retries = 0;

        final json = jsonDecode(response.body) as Map<String, dynamic>;
        final rawList = json['data'] as List? ?? [];
        exercises.addAll(rawList.cast<Map<String, dynamic>>().map(_mapToExercise));

        final meta = json['meta'] as Map<String, dynamic>? ?? {};
        final hasNext = meta['hasNextPage'] == true;
        cursor = meta['nextCursor'] as String?;
        if (!hasNext || cursor == null || cursor.isEmpty) break;

        // Gentle pacing between pages to stay under the rate limit.
        await Future.delayed(const Duration(milliseconds: 350));
      }
    } catch (_) {
      // Return whatever was gathered before the failure.
    }

    return exercises;
  }

  // ── Mapping ─────────────────────────────────────────────────────────────────

  Exercise _mapToExercise(Map<String, dynamic> raw) {
    final bodyParts = List<String>.from(raw['bodyParts'] ?? (raw['bodyPart'] is String ? [raw['bodyPart']] : []));
    final equipments = List<String>.from(raw['equipments'] ?? (raw['equipment'] is String ? [raw['equipment']] : []));
    final targetMuscles = List<String>.from(raw['targetMuscles'] ?? (raw['target'] is String ? [raw['target']] : []));
    final secondaryMuscles = List<String>.from(raw['secondaryMuscles'] ?? []);
    final instructions = raw['instructions'] is List
        ? (raw['instructions'] as List).cast<String>().join('\n')
        : (raw['instructions'] as String? ?? '');
    final name = (raw['name'] as String? ?? '').toLowerCase();

    return Exercise(
      id: raw['exerciseId']?.toString() ?? raw['id']?.toString() ?? name.hashCode.toString(),
      name: _titleCase(name),
      category: bodyParts.isNotEmpty ? bodyParts.first : 'Other',
      primaryMuscles: targetMuscles,
      secondaryMuscles: secondaryMuscles,
      equipment: _normalizeEquipment(equipments),
      difficulty: inferExerciseDifficulty(name, equipments),
      goals: _inferGoals(bodyParts, name),
      locations: _inferLocations(equipments),
      instructions: instructions,
      gifUrl: raw['gifUrl'] as String?,
    );
  }

  // Maps ExerciseDB equipment names to app's format
  List<String> _normalizeEquipment(List<String> raw) {
    const map = {
      'body weight': 'Bodyweight',
      'dumbbell': 'Dumbbells',
      'barbell': 'Barbell',
      'ez barbell': 'Barbell',
      'kettlebell': 'Kettlebells',
      'resistance band': 'Resistance Bands',
      'pull-up bar': 'Pull-up Bar',
      'cable': 'Cable Machine',
      'machine': 'Machine',
      'band': 'Resistance Bands',
      'assisted': 'Machine',
    };
    final normalized = raw.map((e) => map[e.toLowerCase()] ?? _titleCase(e)).toList();
    return normalized.isEmpty ? ['Bodyweight'] : normalized;
  }

  // Infers workout goal tags from body parts / exercise name
  List<String> _inferGoals(List<String> bodyParts, String name) {
    final goals = <String>[];
    final bp = bodyParts.map((b) => b.toLowerCase()).toList();

    if (bp.contains('cardio') || name.contains('run') || name.contains('jump')) {
      goals.add('weight_loss');
      goals.add('endurance');
    }
    if (bp.any((b) => ['chest', 'back', 'shoulders', 'upper arms', 'upper legs'].contains(b))) {
      goals.add('muscle_gain');
      goals.add('general');
    }
    if (bp.contains('waist') || bp.contains('lower legs')) {
      goals.add('weight_loss');
      goals.add('general');
    }
    if (goals.isEmpty) goals.addAll(['general', 'muscle_gain']);
    return goals.toSet().toList();
  }

  // Infers home/gym from equipment. Barbell is intentionally NOT gym-only:
  // home users can own a barbell, so barbell/ez-barbell moves stay home-eligible
  // and are gated by the user's equipment chips (and rack) in
  // GreedyAlgorithm.isEligibleForUser. Only fixed-station gym kit is gym-only.
  List<String> _inferLocations(List<String> raw) {
    final gymOnly = {'cable', 'machine', 'assisted', 'smith machine', 'leverage machine'};
    final hasGymEquip = raw.any((e) => gymOnly.contains(e.toLowerCase()));
    return hasGymEquip ? ['gym'] : ['home', 'gym'];
  }

  // Difficulty inference lives in difficulty_inference.dart (pure Dart, no
  // Firebase) so it can be audited by a standalone script against the full
  // catalog. See that file for the tier policy and keyword rationale.

  String _titleCase(String s) => s.split(' ').map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}').join(' ');
}
